---
title: "Simulation"
author: "Yifei Yu"
date: "2024-10-29"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

load key packages.

```{r}
library(rvest)
library(dplyr)

library(tidyverse)
set.seed(1031)
```


## Check stuff using a simulation

```{r}
sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )

sim_df |> 
  summarize(
    samp_mean = mean(x),
    samp_sd = sd(x)
  )
```


## Writing a simulation function.

```{r}
sim_mean_sd = function(sample_size, true_mean = 10, true_sd = 5) {
  
  sim_df = 
  tibble(
    x = rnorm(sample_size, true_mean, true_sd)
  )

out_df = 
  sim_df |> 
  summarize(
    samp_mean = mean(x),
    samp_sd = sd(x)
  )

return(out_df)
  
}

sim_mean_sd(sample_size = 30, true_mean = 4, true_sd = 12)
sim_mean_sd(true_sd = 12, sample_size = 30, true_mean = 4)
```


run this a lot of times...

```{r}
sim_mean_sd(30)
```


run this using a for loop

```{r}
output = vector("list", 1000)

for (i in 1:1000) {
  
  output[[i]] = sim_mean_sd(30)
  
}

bind_rows(output) |> 
  summarize(
    ave_samp_mean = mean(samp_mean),
    SE_samp_mean = sd(samp_mean)
  )
```



Can I use map instead?

```{r}
sim_res = 
  tibble(
    iter = 1:1000
  ) |> 
  mutate(samp_res = map(iter , sim_mean_sd, sample_size = 30)) |> 
  unnest(samp_res)
```


different sample sizes:

```{r}
sim_res = 
  expand_grid(
    n = c(10, 30, 60, 100),
    iter = 1:1000
  ) |> 
  mutate(samp_res = map(n , sim_mean_sd)) |> 
  unnest(samp_res)
```


```{r}
sim_res |> 
  group_by(n) |> 
  summarize(
    se = sd(samp_mean)
  )
```

```{r}
sim_res |> 
  mutate(
    n = str_c("n = ", n),
    
  ) |> 
  ggplot(aes(x = n, y = samp_mean)) +
  geom_violin()
```


```{r}
sim_res |> 
  filter(n == 10) |> 
  ggplot(aes(x = samp_mean)) +
  geom_histogram()
```


## Do a simple linear regression (SLR)!

```{r}
sim_data = 
  tibble(
    x = rnorm(30, mean = 1, sd =1),
    y = 2 + 3 * x + rnorm(30, 0, 1)
  )

lm_fit = lm(y ~x, data = sim_data)

sim_data |> 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_smooth(method = "lm")
```


Turn this into a function

```{r}
sim_regression = function(n) {
  
  sim_data = 
    tibble(
      x = rnorm(n, mean = 1, sd =1),
      y = 2 + 3 * x + rnorm(n, 0, 1)
  )

  lm_fit = lm(y ~ x, data = sim_data)
  
  out_df = 
    tibble(
      beta0_hat = coef(lm_fit)[1],
      beta1_hat = coef(lm_fit)[2]
    )
  
  return(out_df)
}


sim_res = 
  expand_grid(
    sample_size = 30,
    iter = 1:1000
  ) |> 
  mutate(lm_res = map(sample_size, sim_regression)) |> 
  unnest(lm_res)

sim_res |> 
  ggplot(aes(x = beta0_hat)) +
  geom_histogram()

sim_res |> 
  ggplot(aes(x = beta1_hat)) +
  geom_histogram()

sim_res |> 
  mutate(sample_size = str_c("n = ", sample_size)) |> 
  ggplot(aes(x = sample_size, y = beta1_hat)) +
  geom_boxplot()

sim_res |> 
  filter(sample_size == 30) |> 
  ggplot(aes(x = beta0_hat, y = beta1_hat)) +
  geom_point()
```




## Birthday Problem!

Let's put people in a room.

```{r}
bdays = sample(1:365, size = 10, replace = TRUE)

length(unique(bdays)) < 10
```



```{r}
bday_sim = function(n) {
  
  bdays = sample(1:365, size = n, replace = TRUE)
  
  duplicate = length(unique(bdays)) < n
  
  return(duplicate)
}

bday_sim(10)
```

run this a lot

```{r}
sim_res =
  expand_grid(
    n = c(10, 50),
    iter = 1:10
  ) |> 
  mutate(res = map_lgl(n, bday_sim)) |> 
  group_by(n) |> 
  summarize(prob = mean(res))
```


```{r}
sim_res =
  expand_grid(
    n = 2:50,
    iter = 1:10000
  ) |> 
  mutate(res = map_lgl(n, bday_sim)) |> 
  group_by(n) |> 
  summarize(prob = mean(res))

sim_res |> 
  ggplot(aes(x = n, y = prob)) +
  geom_line()
```




